export const foodData = [
  {
    id: 1,
    name: "Paneer Butter Masala",
    category: "North Indian",
    vegetarian: true,
    price: 220,
    discount: 15,
    finalPrice: 187,
    rating: 4.6,
    deliveryTime: "30 mins",
    isPromoted: true,
    tags: ["Paneer", "Butter", "Curry"],
    distance: 2.1,
    imageUrl:
      "https://b.zmtcdn.com/data/dish_photos/9ca/c6a1e8d9e70db2764fc378e9428f39ca.jpg?output-format=webp",
    description: "Cottage cheese cooked in creamy tomato gravy.",
  },
  {
    id: 2,
    name: "Chicken Biryani",
    category: "Hyderabadi",
    vegetarian: false,
    price: 280,
    discount: 20,
    finalPrice: 224,
    rating: 4.8,
    deliveryTime: "40 mins",
    isPromoted: false,
    tags: ["Spicy", "Rice", "Chicken"],
    distance: 3.4,
    imageUrl:
      "https://b.zmtcdn.com/data/dish_photos/724/770a36c4a49273b067a1670290d2f724.jpg?output-format=webp",
    description: "Aromatic basmati rice with flavorful chicken.",
  },
  {
    id: 3,
    name: "Veg Hakka Noodles",
    category: "Chinese",
    vegetarian: true,
    price: 180,
    discount: 10,
    finalPrice: 162,
    rating: 4.3,
    deliveryTime: "25 mins",
    isPromoted: true,
    tags: ["Noodles", "Spicy", "Popular"],
    distance: 1.7,
    imageUrl:
      "https://b.zmtcdn.com/data/dish_photos/750/cc718e046a814b8f739aa33fe0de3750.jpeg?output-format=webp",
    description: "Stir-fried noodles with veggies & sauces.",
  },
  {
    id: 4,
    name: "Margherita Pizza",
    category: "Italian",
    vegetarian: true,
    price: 260,
    discount: 12,
    finalPrice: 229,
    rating: 4.5,
    deliveryTime: "35 mins",
    isPromoted: false,
    tags: ["Pizza", "Cheese"],
    distance: 2.0,
    imageUrl:
      "https://b.zmtcdn.com/data/dish_photos/960/8adffba55144308bdb04e1c8aabf2960.jpeg?output-format=webp",
    description: "Classic pizza with cheese and basil.",
  },
  {
    id: 5,
    name: "Cheeseburger",
    category: "American",
    vegetarian: false,
    price: 190,
    discount: 5,
    finalPrice: 180,
    rating: 4.2,
    deliveryTime: "28 mins",
    isPromoted: false,
    tags: ["Burger", "Cheese"],
    distance: 1.5,
    imageUrl:
      "https://b.zmtcdn.com/data/dish_photos/198/e97a813bdb064f84eb07b82c4f3d9198.jpeg",
    description: "Juicy beef patty with melted cheese.",
  },
  {
    id: 6,
    name: "Masala Dosa",
    category: "South Indian",
    vegetarian: true,
    price: 120,
    discount: 8,
    finalPrice: 110,
    rating: 4.7,
    deliveryTime: "20 mins",
    isPromoted: true,
    tags: ["Dosa", "Crispy", "Potato"],
    distance: 1.2,
    imageUrl:
      "https://b.zmtcdn.com/data/pictures/3/21515843/ac7340ecbaf11b317e6e7f04318fa5c6_o2_featured_v2.jpg?output-format=webp",
    description: "Crispy dosa with spicy potato filling.",
  },
  {
    id: 7,
    name: "Sushi Platter",
    category: "Japanese",
    vegetarian: false,
    price: 500,
    discount: 10,
    finalPrice: 450,
    rating: 4.9,
    deliveryTime: "45 mins",
    isPromoted: false,
    tags: ["Sushi", "Fish", "Seafood"],
    distance: 4.2,
    imageUrl:
      "https://b.zmtcdn.com/data/pictures/4/21657174/181aa939d06ac84720e43670ba6b843e_o2_featured_v2.jpg?output-format=webp",
    description: "Assorted sushi rolls with wasabi & soy.",
  },
  {
    id: 8,
    name: "Chole Bhature",
    category: "Punjabi",
    vegetarian: true,
    price: 160,
    discount: 10,
    finalPrice: 144,
    rating: 4.5,
    deliveryTime: "25 mins",
    isPromoted: true,
    tags: ["Chole", "Bhature", "Spicy"],
    distance: 2.8,
    imageUrl:
      "https://b.zmtcdn.com/data/dish_photos/4a4/bfd7d923ef594c1484a64be883cf94a4.jpeg?output-format=webp",
    description: "Fluffy bhature with spicy chickpeas.",
  },
  {
    id: 9,
    name: "Tandoori Chicken",
    category: "Indian Grill",
    vegetarian: false,
    price: 320,
    discount: 18,
    finalPrice: 262,
    rating: 4.6,
    deliveryTime: "38 mins",
    isPromoted: false,
    tags: ["Tandoor", "Grilled"],
    distance: 3.0,
    imageUrl:
      "https://b.zmtcdn.com/data/dish_photos/928/ba570fc3d9cb24b0efa3db529a405928.jpg?output-format=webp",
    description: "Grilled chicken with Indian spices.",
  },
  {
    id: 10,
    name: "Pav Bhaji",
    category: "Street Food",
    vegetarian: true,
    price: 140,
    discount: 10,
    finalPrice: 126,
    rating: 4.4,
    deliveryTime: "20 mins",
    isPromoted: false,
    tags: ["Pav", "Butter", "Spicy"],
    distance: 1.9,
    imageUrl:
      "https://b.zmtcdn.com/data/dish_photos/edd/c006cc6e6f177857ada68510b64e0edd.jpeg?output-format=webp",
    description: "Buttery buns with mashed spicy bhaji.",
  },
  {
    id: 11,
    name: "Falafel Wrap",
    category: "Middle Eastern",
    vegetarian: true,
    price: 200,
    discount: 12,
    finalPrice: 176,
    rating: 4.3,
    deliveryTime: "30 mins",
    isPromoted: true,
    tags: ["Wrap", "Falafel", "Healthy"],
    distance: 2.3,
    imageUrl:
      "https://b.zmtcdn.com/data/dish_photos/5a6/d24bd31f75e1eea236bcf5b1492fa5a6.jpeg?output-format=webp",
    description: "Chickpea fritters wrapped with veggies.",
  },
  {
    id: 12,
    name: "Fish Curry Rice",
    category: "Coastal",
    vegetarian: false,
    price: 270,
    discount: 10,
    finalPrice: 243,
    rating: 4.6,
    deliveryTime: "35 mins",
    isPromoted: false,
    tags: ["Fish", "Curry", "Rice"],
    distance: 3.6,
    imageUrl:
      "https://b.zmtcdn.com/data/dish_photos/71c/328ebbdaae799be576eb3bbd98d2c71c.jpg?output-format=webp",
    description: "Tangy fish curry with steamed rice.",
  },
  {
    id: 13,
    name: "Idli Sambar",
    category: "South Indian",
    vegetarian: true,
    price: 100,
    discount: 10,
    finalPrice: 90,
    rating: 4.5,
    deliveryTime: "15 mins",
    isPromoted: true,
    tags: ["Idli", "Sambar", "Healthy"],
    distance: 1.0,
    imageUrl:
      "https://b.zmtcdn.com/data/dish_photos/8ef/b4c7d0fee01a610c553fcd8aa82198ef.jpeg?output-format=webp",
    description: "Steamed rice cakes with hot sambar.",
  },
  {
    id: 14,
    name: "Fried Rice & Manchurian",
    category: "Chinese",
    vegetarian: true,
    price: 200,
    discount: 15,
    finalPrice: 170,
    rating: 4.4,
    deliveryTime: "22 mins",
    isPromoted: false,
    tags: ["Manchurian", "Rice", "Combo"],
    distance: 2.0,
    imageUrl:
      "https://b.zmtcdn.com/data/dish_photos/792/b797276a11673901a0d14e96629f7792.jpeg?output-format=webp",
    description: "Chinese fried rice with veg manchurian balls.",
  },
  {
    id: 15,
    name: "Chocolate Lava Cake",
    category: "Dessert",
    vegetarian: true,
    price: 120,
    discount: 5,
    finalPrice: 114,
    rating: 4.9,
    deliveryTime: "15 mins",
    isPromoted: true,
    tags: ["Dessert", "Chocolate", "Cake"],
    distance: 1.1,
    imageUrl:
      "https://b.zmtcdn.com/data/dish_photos/1f6/fe2d9ed54da88b719cfc93ad2b99e1f6.jpeg?output-format=webp",
    description: "Warm chocolate cake with gooey center.",
  },
];
